title: Arsyid Aldi pratama
logo: /images/Arsyid_Aldi_Pratama__Business_CIRCLE-min.png
#description: 
#Experienced in Business and Data Analyst with 4+ years of experience  in analyzing business processes, evaluating opportunities, and delivering actionable insights. Adept at data modeling, data analysis, and strategic planning, with a proven ability to streamline operations and enhance decision-making. Expertise including gathering, data visualisation, process improvement, and problem-solving .Proactive, adaptable, and motivated to drive business growth in dynamic environments.
#show_downloads: true

theme: jekyll-theme-minimal
