title: "Arsyid Aldi Pratama"
logo: "/images/Arsyid_Aldi_Pratama__Business_CIRCLE-min.png"
description: >
  Experienced in Business and Data Analyst with 4+ years of experience in analyzing business processes, evaluating opportunities, and delivering actionable insights  

  Currently work in PT. Rupa Aestetika Teknologi Aktual as a Operation Excellence Data Analyst  

  [View My LinkedIn Profile](https://www.linkedin.com/in/arsyid-aldi-pratama-382750138/)


# Tema menggunakan remote_theme agar lebih fleksibel
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
