title: "Arsyid Aldi Pratama"
logo: "/images/Arsyid_Aldi_Pratama__Business_CIRCLE-min.png"
description: >
  <div style="text-align:justify; font-family:'Open Sans', Arial, sans-serif; line-height:1.6;">
    Experienced in Business and Data Analyst with 4+ years of experience in analyzing business processes, 
    evaluating opportunities, and delivering actionable insights. Expertise including gathering, data visualisation, 
    process improvement, and problem-solving.
    <br><br>
    Currently work in PT. Rupa Aestetika Teknologi Aktual as a Operation Excellence Data Analyst
    <br><br>
    <a href="https://www.linkedin.com/in/arsyid-aldi-pratama-382750138/">View My LinkedIn Profile</a>
  </div>
