title: Arsyid Aldi Pratama
logo: /images/Arsyid_Aldi_Pratama__Business_CIRCLE-min.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced in Business and Data Analyst with 4+ years of experience  in analyzing business processes, evaluating opportunities, and delivering actionable insights 
  <br><br>
  Currently work in PT. Rupa Aestetika Teknologi Aktual as a Operation Excellence Data Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/arsyid-aldi-pratama-382750138/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
